name: Publish to crates.io

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: publish crates
        uses: katyo/publish-crates@v2
        id: publish-crates
        with:
          dry-run: ${{ github.event_name != 'push' }}
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: if my-crate published
        if: fromJSON(steps.publish-crates.outputs.published).*
        run: |
          LIST="${{ join(fromJSON(steps.publish-crates.outputs.published).*.name, ', ') }}"
          echo "Published crates: $LIST"
